export * as logo from './logo.png';
export * as book1 from './book_1.png';
export * as onePiece_1 from './one_piece_1.jpg';
export * as slide1 from './silder_1.png';
export * as slide2 from './silder_2.png';
export * as slide3 from './silder_3.png';
export * as banner_1 from './banner_01.png';
export * as coming_soon from './coming.png';
export * as default_banner from './default_banner.webp';
